### ISSUE TITLE
MC Log error code -805306369

### ISSUE THREAD

**Issue by WesleyBryie** [PrismLauncher/refraction#211]
I used the bot in #quick-support on the server, and it said that my log had no found issues. I would like to suggest that error code "-805306369" is due to a lack of memory. Not sure how common this error is.

**Comment by TayouVR** [comment]
doing a quick internet search it does seem to indicate that the JVM ran out of memory, we should add a response for that exit code then to instruct the user to increase their java memory if their system resources allow for it.

**Comment by WesleyBryie** [comment]
I am working on a quick pull/commit that should include the error code in the same section as the specific "OOM" detecter.

**Comment by WesleyBryie** [comment]
Resolved by #329
